version: "3.7"

services:
  laravel:
    build:
      dockerfile: ./docker/Dockerfile
    networks:
        - laravel-network
    environment:
        - DB_HOST=mysql
        - DB_PORT=3306
        - DB_DATABASE=laravel
        - DB_USERNAME=paxton
        - DB_PASSWORD=oolong20020222
    platform: "linux/amd64"
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: oolong20020222
      MYSQL_DATABASE: laravel
      MYSQL_USER: paxton
      MYSQL_PASSWORD: oolong20020222
    networks:
      - laravel-network
    volumes:
      - laravel-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  nginx:
    build:
      dockerfile: ./docker/Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
        - laravel-network

networks:
  laravel-network:

volumes:
  laravel-mysql:
