version: "3.7"

services:
  laravel:
    build:
      dockerfile: ./docker/Dockerfile
    networks:
        - laravel-network
    env_file: .env.prod
    # platform: "linux/amd64"
    depends_on:
      - mysql_prod
      - migration
      - redis_prod
    volumes:
      - laravel-fpm-public:/var/www/html/public
  laravel_swoole:
    build:
      dockerfile: ./docker/Dockerfile.swoole
    networks:
        - laravel-network
    env_file: .env.prod
    # platform: "linux/amd64"
    depends_on:
      - mysql_prod
      - migration
      - redis_prod
    # ports:
      # - "9000:9000"
  migration:
    build:
      dockerfile: ./docker/Dockerfile.migration
    env_file: .env.prod
    # platform: "linux/amd64"
    depends_on:
      - mysql_prod
    networks:
      - laravel-network
  mysql_prod:
    image: mysql:8.0
    env_file: .env.prod
    networks:
      - laravel-network
    volumes:
      - laravel-mysql:/var/lib/mysql
  redis_prod:
    image: 'bitnami/redis:latest'
    env_file: .env.prod
    volumes:
      - laravel-redis:/opt/bitnami/redis/mounted-etc/users.acl
    networks:
      - laravel-network
  nginx:
    build:
      dockerfile: ./docker/Dockerfile.nginx
    ports:
      - "8088:80"
      - "4433:443"
    networks:
        - laravel-network
    depends_on:
      - laravel
    volumes:
      - laravel-fpm-public:/var/www/html/public
  nginx_swoole:
    build:
      dockerfile: ./docker/Dockerfile.nginx.swoole
    ports:
      - "8001:80"
      - "4431:443"
    networks:
        - laravel-network
    depends_on:
      - laravel_swoole
networks:
  laravel-network:

volumes:
  laravel-mysql:
  laravel-redis:
  laravel-fpm-public: